# Generated by Django 4.0 on 2022-09-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_dateformat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateformat',
            name='format',
            field=models.CharField(max_length=10),
        ),
    ]
