# Generated by Django 4.0 on 2022-09-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0005_alter_user_account_default_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='default_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='default_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
