# Generated by Django 4.0 on 2022-10-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0006_alter_user_account_default_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
