# Generated by Django 4.0 on 2022-08-13 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customuser.user_account'),
        ),
    ]
