# Generated by Django 4.0 on 2022-09-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_name',
        ),
        migrations.AddField(
            model_name='account',
            name='account_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
