# Generated by Django 4.0 on 2022-09-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_account_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_description',
        ),
        migrations.AddField(
            model_name='account',
            name='account_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
