# Generated by Django 4.0 on 2022-09-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_account_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_name',
            new_name='account_id',
        ),
        migrations.AddField(
            model_name='account',
            name='account_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
