# Generated by Django 4.0 on 2022-10-04 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0006_alter_user_account_default_currency_and_more'),
        ('accounts', '0007_rename_account_name_account_account_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('account_id', 'user_account')},
        ),
    ]
