# Generated by Django 4.0 on 2022-08-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_transaction_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sum_of_transactions',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
