# Generated by Django 4.0 on 2022-10-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sum_of_transactions',
            field=models.FloatField(),
        ),
    ]
