# Generated by Django 4.0 on 2022-10-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transaction_sum_of_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sum_of_transactions',
            field=models.IntegerField(),
        ),
    ]
