# Generated by Django 4.0 on 2022-10-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_invoiceitem_invoice_alter_invoiceitem_product'),
        ('transactions', '0008_alter_transaction_sum_of_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='invoice',
            field=models.ManyToManyField(blank=True, null=True, to='invoice.Invoice'),
        ),
    ]
