# Generated by Django 4.0 on 2022-09-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_alter_bank_account_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_account',
            name='name',
        ),
    ]
