# Generated by Django 4.0 on 2022-09-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_remove_bank_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_account',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
