# Generated by Django 4.0 on 2022-09-26 14:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_alter_bank_account_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_account',
            name='id',
        ),
        migrations.AddField(
            model_name='bank_account',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
