# Generated by Django 4.0 on 2022-09-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
