# Generated by Django 4.0 on 2022-10-09 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
    ]
