# Generated by Django 4.0 on 2022-08-13 05:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customuser', '0001_initial'),
        ('company', '0002_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_name', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('order_sum', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.contractor')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customuser.user_account')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
