# Generated by Django 4.0 on 2022-10-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_order_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_status',
            options={'verbose_name': 'Order status', 'verbose_name_plural': 'Order stats'},
        ),
    ]
