# Generated by Django 4.0 on 2022-10-02 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_account_name_account_account_id_and_more'),
        ('invoice', '0006_alter_invoice_invoice_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
            preserve_default=False,
        ),
    ]
