# Generated by Django 4.0 on 2022-10-02 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_invoice_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Invoice status',
                'verbose_name_plural': 'Invoice stats',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice_status'),
            preserve_default=False,
        ),
    ]
