# Generated by Django 4.0 on 2022-10-02 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_alter_invoiceitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='price',
        ),
    ]
