# Generated by Django 4.0 on 2022-10-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_remove_invoiceitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
            preserve_default=False,
        ),
    ]
