# Generated by Django 4.0 on 2022-10-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_alter_invoiceitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_status',
            field=models.CharField(max_length=255),
        ),
    ]
