# Generated by Django 4.0 on 2022-10-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_alter_invoice_invoice_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice_status',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_status',
            field=models.CharField(choices=[(0, 'Draft'), (1, 'Sent'), (2, 'Paid'), (3, 'Canceled')], max_length=255),
        ),
    ]
