# Generated by Django 4.0 on 2022-10-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_alter_invoice_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Paid', 'Paid'), ('Partially Paid', 'Partially Paid'), ('Canceled', 'Canceled')], max_length=255),
        ),
    ]
