# Generated by Django 4.0 on 2022-09-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='contractor_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
