# Generated by Django 4.0 on 2022-10-04 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0006_alter_user_account_default_currency_and_more'),
        ('contractors', '0002_alter_contractor_contractor_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contractor',
            unique_together={('contractor_name', 'user_account')},
        ),
    ]
