# Generated by Django 4.0 on 2022-10-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0003_alter_contractor_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='contractor_name',
            field=models.CharField(max_length=255),
        ),
    ]
